name: CI/CD Pipeline 1.0
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - master
jobs:
#Sonar Cloud
  sonarcloud-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=crislb27
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.python.version=3.9
#Snyk
  snyk-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: code test
          args: --severity-threshold=high --org=crislb27

  #GitHub advance security
  ghas-security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Dependency Review
        if: github.event_name == 'pull_request'
        uses: actions/dependency-review-action@v3
        with:
          fail-on-severity: high

      - name: Secret Scanning (Gitleaks)
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#Corto circuito
  build-test-push:
    needs: [sonarcloud-scan, snyk-scan, ghas-security]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    env:
      APP_VERSION: "1.0"
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/evaluacion3-app:1.0 .
      - name: Run Tests
        run: |
          docker run --rm ${{ secrets.DOCKER_USERNAME }}/evaluacion3-app:1.0 pytest test_app.py
#Docker Scout
      - name: Docker Scout
        uses: docker/scout-action@v1
        with:
          command: cves
          image: ${{ secrets.DOCKER_USERNAME }}/evaluacion3-app:1.0
          ignore-unchanged: true
          only-severities: critical,high
          exit-code: true
          dockerhub-user: ${{ secrets.DOCKER_USERNAME }}
          dockerhub-password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/evaluacion3-app:1.0
